/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Clientes;
import conexaoClasse.ClientesDAO;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gabri
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cadastrarCPFCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cadastrarEnderecoCliente = new javax.swing.JTextField();
        cadastrarCodigoVerificacao = new javax.swing.JTextField();
        cadastrarNomeCliente = new javax.swing.JTextField();
        cadastrarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercearia GMW");

        jPanel1.setMaximumSize(new java.awt.Dimension(763, 564));
        jPanel1.setMinimumSize(new java.awt.Dimension(763, 564));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel6.setText("Preencha os campos abaixo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 80, 220, 70);

        cadastrarCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCPFClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarCPFCliente);
        cadastrarCPFCliente.setBounds(240, 270, 290, 30);

        jLabel13.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel13.setText("CPF");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(240, 240, 80, 20);

        jLabel7.setFont(new java.awt.Font("Constantia", 2, 36)); // NOI18N
        jLabel7.setText("Cadastro de Clientes");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 50, 320, 70);

        jLabel14.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel14.setText("Endereço");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(240, 320, 80, 20);

        jLabel15.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel15.setText("Código de Verificação");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(240, 410, 150, 20);

        jLabel16.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel16.setText("Nome");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(240, 150, 80, 20);

        cadastrarEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEnderecoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarEnderecoCliente);
        cadastrarEnderecoCliente.setBounds(240, 350, 290, 30);

        cadastrarCodigoVerificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCodigoVerificacaoActionPerformed(evt);
            }
        });
        cadastrarCodigoVerificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarCodigoVerificacaoKeyPressed(evt);
            }
        });
        jPanel1.add(cadastrarCodigoVerificacao);
        cadastrarCodigoVerificacao.setBounds(240, 440, 290, 30);

        cadastrarNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNomeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarNomeCliente);
        cadastrarNomeCliente.setBounds(240, 180, 290, 30);

        cadastrarCliente.setBackground(new java.awt.Color(10, 17, 61));
        cadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarCliente.setText("Cadastrar");
        cadastrarCliente.setAutoscrolls(true);
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarCliente);
        cadastrarCliente.setBounds(300, 510, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarCPFClienteActionPerformed

    private void cadastrarEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarEnderecoClienteActionPerformed

    private void cadastrarCodigoVerificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCodigoVerificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarCodigoVerificacaoActionPerformed

    private void cadastrarNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarNomeClienteActionPerformed

    private void cadastrarCodigoVerificacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarCodigoVerificacaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarCodigoVerificacaoKeyPressed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        
        Clientes cliente = new Clientes();
        ClientesDAO clienteDAO = new ClientesDAO();
        
        cliente.setNome(cadastrarNomeCliente.getText());
        cliente.setCPF(cadastrarCPFCliente.getText());
        cliente.setEndereco(cadastrarEnderecoCliente.getText());
        cliente.setSenha(cadastrarCodigoVerificacao.getText());
        clienteDAO.cria(cliente);
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mainCadastroCliente() {
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCadastroCliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadastrarCPFCliente;
    private javax.swing.JButton cadastrarCliente;
    private javax.swing.JTextField cadastrarCodigoVerificacao;
    private javax.swing.JTextField cadastrarEnderecoCliente;
    private javax.swing.JTextField cadastrarNomeCliente;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
