/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author gabri
 */
public class TelaPedido extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        visualizarIDPedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        adicionarNomeCliente = new javax.swing.JTextField();
        removerProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pesquisaProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adicionarQuantidadeProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        VisualizarValorTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adicionarCarrinho = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adicionarCPFCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        limparCarrinho = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        visualizarNomeCliente = new javax.swing.JTextField();
        visualizarCPFCliente = new javax.swing.JTextField();
        adicionarCVCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        visualizarEnderecoCliente = new javax.swing.JTextField();
        finalizarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercearia GMW");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new java.awt.CardLayout());

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1080, 40, 80, 20);

        visualizarIDPedido.setEditable(false);
        jPanel1.add(visualizarIDPedido);
        visualizarIDPedido.setBounds(540, 700, 80, 30);

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel1.setText("CPF Cliente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1080, 110, 80, 20);

        adicionarNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNomeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(adicionarNomeCliente);
        adicionarNomeCliente.setBounds(1080, 60, 280, 30);

        removerProduto.setBackground(new java.awt.Color(110, 232, 194));
        removerProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removerProduto.setText("Remover Produto");
        removerProduto.setAutoscrolls(true);
        removerProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(removerProduto);
        removerProduto.setBounds(60, 540, 190, 40);

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel3.setText("Produto");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 360, 80, 20);

        pesquisaProduto.setEditable(false);
        pesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisaProduto);
        pesquisaProduto.setBounds(60, 390, 200, 30);

        jLabel4.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 360, 90, 20);

        adicionarQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarQuantidadeProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(adicionarQuantidadeProduto);
        adicionarQuantidadeProduto.setBounds(300, 390, 120, 30);

        jLabel5.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel5.setText("ID do Pedido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(540, 680, 100, 20);

        VisualizarValorTotal.setEditable(false);
        VisualizarValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarValorTotalActionPerformed(evt);
            }
        });
        jPanel1.add(VisualizarValorTotal);
        VisualizarValorTotal.setBounds(540, 630, 170, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Produto", "Produto", "Marca", "Departamento", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(540, 40, 440, 520);

        adicionarCarrinho.setBackground(new java.awt.Color(10, 17, 61));
        adicionarCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adicionarCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        adicionarCarrinho.setText("Adicionar ao carrinho");
        adicionarCarrinho.setAutoscrolls(true);
        adicionarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(adicionarCarrinho);
        adicionarCarrinho.setBounds(60, 460, 190, 40);

        jLabel6.setFont(new java.awt.Font("Constantia", 2, 40)); // NOI18N
        jLabel6.setText("Faça o pedido aqui");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 250, 320, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\Downloads\\gmw.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1050, 250, 420, 250);
        jPanel1.add(adicionarCPFCliente);
        adicionarCPFCliente.setBounds(1080, 130, 280, 30);

        jLabel7.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel7.setText("Valor total da compra");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(540, 610, 150, 20);
        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(230, -50, 0, 1);

        limparCarrinho.setBackground(new java.awt.Color(110, 232, 194));
        limparCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limparCarrinho.setText("Limpar Carrinho");
        limparCarrinho.setAutoscrolls(true);
        limparCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(limparCarrinho);
        limparCarrinho.setBounds(770, 650, 190, 40);

        jTabbedPane3.addTab("Pedido", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\Downloads\\carrinho1.png") // NOI18N
        );
        jLabel9.setText("                                                   1");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(1100, 200, 400, 270);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produto", "Produto", "Categoria", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 110, 420, 480);

        jLabel10.setFont(new java.awt.Font("Constantia", 2, 36)); // NOI18N
        jLabel10.setText("Produtos no carrinho");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(90, 40, 330, 70);

        jLabel11.setFont(new java.awt.Font("Constantia", 2, 24)); // NOI18N
        jLabel11.setText("Confirme os dados do cliente");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(600, 140, 330, 60);

        jLabel12.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel12.setText("Código de Verificação");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(610, 460, 180, 20);

        visualizarNomeCliente.setEditable(false);
        visualizarNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarNomeClienteActionPerformed(evt);
            }
        });
        jPanel2.add(visualizarNomeCliente);
        visualizarNomeCliente.setBounds(610, 240, 290, 30);

        visualizarCPFCliente.setEditable(false);
        visualizarCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarCPFClienteActionPerformed(evt);
            }
        });
        jPanel2.add(visualizarCPFCliente);
        visualizarCPFCliente.setBounds(610, 320, 290, 30);

        adicionarCVCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCVClienteActionPerformed(evt);
            }
        });
        jPanel2.add(adicionarCVCliente);
        adicionarCVCliente.setBounds(610, 490, 100, 30);

        jLabel13.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel13.setText("Nome");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(610, 210, 80, 20);

        jLabel14.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel14.setText("CPF");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(610, 290, 80, 20);

        jLabel15.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel15.setText("Endereço");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(610, 370, 80, 20);

        visualizarEnderecoCliente.setEditable(false);
        visualizarEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarEnderecoClienteActionPerformed(evt);
            }
        });
        jPanel2.add(visualizarEnderecoCliente);
        visualizarEnderecoCliente.setBounds(610, 400, 290, 30);

        finalizarPedido.setBackground(new java.awt.Color(10, 17, 61));
        finalizarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finalizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        finalizarPedido.setText("Finalizar Pedido");
        finalizarPedido.setAutoscrolls(true);
        finalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(finalizarPedido);
        finalizarPedido.setBounds(730, 490, 180, 30);

        jTabbedPane3.addTab("Carrinho", jPanel2);

        getContentPane().add(jTabbedPane3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void adicionarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarCarrinhoActionPerformed

    private void VisualizarValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizarValorTotalActionPerformed

    private void adicionarQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarQuantidadeProdutoActionPerformed

    private void pesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaProdutoActionPerformed

    private void removerProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerProdutoActionPerformed

    private void adicionarNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarNomeClienteActionPerformed

    private void visualizarNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizarNomeClienteActionPerformed

    private void visualizarCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizarCPFClienteActionPerformed

    private void adicionarCVClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCVClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarCVClienteActionPerformed

    private void visualizarEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizarEnderecoClienteActionPerformed

    private void finalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalizarPedidoActionPerformed

    private void limparCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCarrinhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limparCarrinhoActionPerformed

    public static void pedidos() {
     
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPedido().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VisualizarValorTotal;
    private javax.swing.JTextField adicionarCPFCliente;
    private javax.swing.JTextField adicionarCVCliente;
    private javax.swing.JButton adicionarCarrinho;
    private javax.swing.JTextField adicionarNomeCliente;
    private javax.swing.JTextField adicionarQuantidadeProduto;
    private javax.swing.JButton finalizarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton limparCarrinho;
    private javax.swing.JTextField pesquisaProduto;
    private javax.swing.JButton removerProduto;
    private javax.swing.JTextField visualizarCPFCliente;
    private javax.swing.JTextField visualizarEnderecoCliente;
    private javax.swing.JTextField visualizarIDPedido;
    private javax.swing.JTextField visualizarNomeCliente;
    // End of variables declaration//GEN-END:variables
}
