/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;

/**
 *
 * @author MarianaGressi
 */
public class TelaPrincipalGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalGerente() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUsuario = new javax.swing.JMenu();
        MenuCadastrar = new javax.swing.JMenu();
        CadastraFuncionario = new javax.swing.JMenuItem();
        CadastraProduto = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        ListaCliente = new javax.swing.JMenuItem();
        ListaFuncionario = new javax.swing.JMenuItem();
        ListaVenda = new javax.swing.JMenuItem();
        ListaEstoque = new javax.swing.JMenuItem();
        MenuAgenda = new javax.swing.JMenu();
        MenuAjuda = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem10.setText("jMenuItem10");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercearia MGW");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel6))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel6))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        MenuUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\usuario.png")); // NOI18N
        MenuUsuario.setText("Usuário");
        MenuUsuario.setFont(new java.awt.Font("Constantia", 0, 15)); // NOI18N
        MenuUsuario.setIconTextGap(-2);

        MenuCadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\add usuario.png")); // NOI18N
        MenuCadastrar.setText("Cadastrar");
        MenuCadastrar.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        MenuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarActionPerformed(evt);
            }
        });

        CadastraFuncionario.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        CadastraFuncionario.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\funcionario.png")); // NOI18N
        CadastraFuncionario.setText("Funcionario");
        CadastraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraFuncionarioActionPerformed(evt);
            }
        });
        MenuCadastrar.add(CadastraFuncionario);

        CadastraProduto.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        CadastraProduto.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\produtos.png")); // NOI18N
        CadastraProduto.setText("Produtos");
        CadastraProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraProdutoActionPerformed(evt);
            }
        });
        MenuCadastrar.add(CadastraProduto);

        MenuUsuario.add(MenuCadastrar);

        jMenuBar1.add(MenuUsuario);

        MenuRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\relatorio.png")); // NOI18N
        MenuRelatorio.setText("Relatórios");
        MenuRelatorio.setFont(new java.awt.Font("Constantia", 0, 15)); // NOI18N

        ListaCliente.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ListaCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\cliente.png")); // NOI18N
        ListaCliente.setText("Clientes");
        ListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaClienteActionPerformed(evt);
            }
        });
        MenuRelatorio.add(ListaCliente);

        ListaFuncionario.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ListaFuncionario.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\usuario.png")); // NOI18N
        ListaFuncionario.setText("Funcionarios");
        ListaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaFuncionarioActionPerformed(evt);
            }
        });
        MenuRelatorio.add(ListaFuncionario);

        ListaVenda.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ListaVenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\vendas.png")); // NOI18N
        ListaVenda.setText("Vendas");
        ListaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVendaActionPerformed(evt);
            }
        });
        MenuRelatorio.add(ListaVenda);

        ListaEstoque.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        ListaEstoque.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\carrinho-de-mao.png")); // NOI18N
        ListaEstoque.setText("Estoque");
        ListaEstoque.setToolTipText("");
        MenuRelatorio.add(ListaEstoque);

        jMenuBar1.add(MenuRelatorio);

        MenuAgenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\agenda.png")); // NOI18N
        MenuAgenda.setText("Agenda");
        MenuAgenda.setFont(new java.awt.Font("Constantia", 0, 15)); // NOI18N
        jMenuBar1.add(MenuAgenda);

        MenuAjuda.setIcon(new javax.swing.ImageIcon("C:\\Users\\resid\\Documents\\gmw\\ajudando.png")); // NOI18N
        MenuAjuda.setText("Ajuda");
        MenuAjuda.setFont(new java.awt.Font("Constantia", 0, 15)); // NOI18N
        jMenuBar1.add(MenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public void setString(String string) {
        this.string = string;
    }

    private void ListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaClienteActionPerformed

    private void ListaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaFuncionarioActionPerformed
        TelaListaFuncionario telaListFun = new TelaListaFuncionario();
        jDesktopPane1.add(telaListFun);
        telaListFun.setVisible(true);
    }//GEN-LAST:event_ListaFuncionarioActionPerformed

    private void ListaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaVendaActionPerformed

    private void MenuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarActionPerformed

    }//GEN-LAST:event_MenuCadastrarActionPerformed

    private void CadastraProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraProdutoActionPerformed
        TelaCadastroProduto telaCadPro = new TelaCadastroProduto();
        jDesktopPane1.add(telaCadPro);
        telaCadPro.setVisible(true);
    }//GEN-LAST:event_CadastraProdutoActionPerformed

    private void CadastraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraFuncionarioActionPerformed
        TelaCadastroFuncionario telaCadFun = new TelaCadastroFuncionario();
        jDesktopPane1.add(telaCadFun);
        telaCadFun.setVisible(true);
    }//GEN-LAST:event_CadastraFuncionarioActionPerformed

    /**
     */
    public static void mainPrincipal() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipalGerente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastraFuncionario;
    private javax.swing.JMenuItem CadastraProduto;
    private javax.swing.JMenuItem ListaCliente;
    private javax.swing.JMenuItem ListaEstoque;
    private javax.swing.JMenuItem ListaFuncionario;
    private javax.swing.JMenuItem ListaVenda;
    private javax.swing.JMenu MenuAgenda;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuCadastrar;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
